version: "3"

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    env_file: .env
    volumes:
      - ./app:/app
  mysql:
    image: mariadb
    env_file: .env
    volumes:
        - mysqldata:/var/lib/mysql
    ports:
        - 3306:3306

volumes:
  mysqldata:
